openapi: 3.0.3
info:
  title: OpenAPI schema for template test-terraform-variable
components:
  schemas:
    variables:
      type: object
      required:
      - object_with_attr_default
      - object_with_nest_object
      - simple_object
      properties:
        str:
          title: Str
          type: string
          default: variable-test
          nullable: true
          x-walrus-ui:
            order: 1
        num:
          title: Num
          type: number
          default: 123
          nullable: true
          x-walrus-ui:
            order: 2
        bool:
          title: Bool
          type: boolean
          default: false
          nullable: true
          x-walrus-ui:
            order: 3
        def_str:
          title: Def Str
          type: string
          default: variable-test
          nullable: true
          x-walrus-ui:
            order: 4
        def_num:
          title: Def Num
          type: number
          default: 123
          nullable: true
          x-walrus-ui:
            order: 5
        def_bool:
          title: Def Bool
          type: boolean
          default: true
          nullable: true
          x-walrus-ui:
            order: 6
        list_string:
          title: List String
          type: array
          default:
          - a1
          - a2
          items:
            type: string
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 7
        list_number:
          title: List Number
          type: array
          default:
          - 80
          - 443
          items:
            type: number
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 8
        list_bool:
          title: List Bool
          type: array
          default:
          - true
          - false
          items:
            type: boolean
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 9
        list_object:
          title: List Object
          type: array
          items:
            properties:
              age:
                title: Age
                type: number
                x-walrus-ui:
                  order: 2
              email:
                nullable: true
                properties:
                  address:
                    title: Address
                    type: string
                    x-walrus-ui:
                      order: 1
                  domain:
                    default: test.com
                    nullable: true
                    title: Domain
                    type: string
                    x-walrus-ui:
                      order: 2
                required:
                - address
                title: Email
                type: object
                x-walrus-ui:
                  colSpan: 12
                  order: 3
              name:
                title: Name
                type: string
                x-walrus-ui:
                  order: 1
            required:
            - age
            - name
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 10
        list_list_str:
          title: List List Str
          type: array
          default:
          - - a1
          items:
            items:
              type: string
            type: array
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 11
        list_map_string:
          title: List Map String
          type: array
          description: List of maps containing node pools
          default:
          - name: default-node-pool
          items:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 12
        list_map_any:
          title: List Map Any
          type: array
          description: List of maps containing node pools
          default:
          - name: default-node-pool
          items:
            additionalProperties:
              type: object
              x-walrus-ui:
                colSpan: 12
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 13
        list_any:
          title: List Any
          type: array
          default:
          - - a1
          items:
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 14
        def_list_string:
          title: Def List String
          type: array
          default:
          - a1
          - a2
          items:
            type: string
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 15
        def_list_number:
          title: Def List Number
          type: array
          default:
          - 80
          - 443
          items:
            type: number
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 16
        def_list_bool:
          title: Def List Bool
          type: array
          default:
          - true
          - false
          items:
            type: boolean
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 17
        def_list_object:
          title: Def List Object
          type: array
          default:
          - age: 23
            email:
              address: bob
              domain: example.com
            name: Bob
          items:
            properties:
              age:
                title: Age
                type: number
              email:
                properties:
                  address:
                    title: Address
                    type: string
                  domain:
                    title: Domain
                    type: string
                required:
                - address
                - domain
                title: Email
                type: object
                x-walrus-ui:
                  colSpan: 12
              name:
                title: Name
                type: string
            required:
            - age
            - email
            - name
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 18
        def_list_list_str:
          title: Def List List Str
          type: array
          default:
          - - a1
          items:
            items:
              type: string
            type: array
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 19
        def_list_map_string:
          title: Def List Map String
          type: array
          description: List of maps containing node pools
          default:
          - name: default-node-pool
          items:
            properties:
              name:
                title: Name
                type: string
            required:
            - name
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 20
        def_list_map_any:
          title: Def List Map Any
          type: array
          description: List of maps containing node pools
          default:
          - name: default-node-pool
          items:
            properties:
              name:
                title: Name
                type: string
            required:
            - name
            type: object
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 21
        def_list_any:
          title: Def List Any
          type: array
          default:
          - - a1
          items:
            items:
              type: string
            type: array
            x-walrus-ui:
              colSpan: 12
          nullable: true
          x-walrus-ui:
            colSpan: 12
            order: 22
        map_str:
          title: Map Str
          type: object
          default:
            age2: "30"
            email2: john@example.com
            name2: John
          nullable: true
          additionalProperties:
            type: string
          x-walrus-ui:
            colSpan: 12
            order: 23
        map_number:
          title: Map Number
          type: object
          default:
            port: 80
          nullable: true
          additionalProperties:
            type: number
          x-walrus-ui:
            colSpan: 12
            order: 24
        map_bool:
          title: Map Bool
          type: object
          default:
            isNow: true
          nullable: true
          additionalProperties:
            type: boolean
          x-walrus-ui:
            colSpan: 12
            order: 25
        map_any:
          title: Map Any
          type: object
          default:
            name: John
          nullable: true
          additionalProperties:
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            order: 26
        def_map_str:
          title: Def Map Str
          type: object
          default:
            age2: "30"
            email2: john@example.com
            name2: John
          nullable: true
          required:
          - age2
          - email2
          - name2
          properties:
            age2:
              title: Age2
              type: string
            email2:
              title: Email2
              type: string
            name2:
              title: Name2
              type: string
          x-walrus-ui:
            colSpan: 12
            order: 27
        def_map_number:
          title: Def Map Number
          type: object
          default:
            port: 80
          nullable: true
          required:
          - port
          properties:
            port:
              title: Port
              type: number
          x-walrus-ui:
            colSpan: 12
            order: 28
        def_map_bool:
          title: Def Map Bool
          type: object
          default:
            isNow: true
          nullable: true
          required:
          - isNow
          properties:
            isNow:
              title: Isnow
              type: boolean
          x-walrus-ui:
            colSpan: 12
            order: 29
        def_map_any:
          title: Def Map Any
          type: object
          default:
            name: John
          nullable: true
          required:
          - name
          properties:
            name:
              title: Name
              type: string
          x-walrus-ui:
            colSpan: 12
            order: 30
        simple_object:
          title: Simple Object
          type: object
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 31
        object_with_default:
          title: Object With Default
          type: object
          default:
            age: 23
            name: Bob
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 32
        object_with_attr_default:
          title: Object With Attr Default
          type: object
          properties:
            age:
              default: 23
              nullable: true
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            name:
              default: Bob
              nullable: true
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 33
        object_with_nest_object:
          title: Object With Nest Object
          type: object
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              nullable: true
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: test.com
                  nullable: true
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 34
        object_with_default_and_nest_object:
          title: Object With Default And Nest Object
          type: object
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              nullable: true
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: test.com
                  nullable: true
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 35
        object_with_default_and_nest_object2:
          title: Object With Default And Nest Object2
          type: object
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              nullable: true
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: test.com
                  nullable: true
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 36
        object_with_default_and_nest_object3:
          title: Object With Default And Nest Object3
          type: object
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              nullable: true
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: attr.com
                  nullable: true
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 37
        simple_object_with_default:
          title: Simple Object With Default
          type: object
          default:
            age: 23
            name: Bob
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
            name:
              title: Name
              type: string
          x-walrus-ui:
            colSpan: 12
            order: 38
