openapi: 3.0.3
info:
  title: OpenAPI schema for template object
components:
  schemas:
    variables:
      type: object
      required:
      - object_with_attr_default
      - object_with_nest_object
      properties:
        object_with_default:
          title: Object With Default
          type: object
          default:
            age: 23
            name: Bob
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 1
        object_with_attr_default:
          title: Object With Attr Default
          type: object
          properties:
            age:
              default: 23
              nullable: true
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            name:
              default: Bob
              nullable: true
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 2
        object_with_nest_object:
          title: Object With Nest Object
          type: object
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              nullable: true
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: test.com
                  nullable: true
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 3
        object_with_default_and_nest_object:
          title: Object With Default And Nest Object
          type: object
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              nullable: true
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: test.com
                  nullable: true
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 4
        object_with_default_and_nest_object2:
          title: Object With Default And Nest Object2
          type: object
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              nullable: true
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: test.com
                  nullable: true
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 5
        object_with_default_and_nest_object3:
          title: Object With Default And Nest Object3
          type: object
          nullable: true
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              nullable: true
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: attr.com
                  nullable: true
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            order: 6
