openapi: 3.0.3
info:
  title: OpenAPI schema for template issue-1688
components:
  schemas:
    variables:
      type: object
      properties:
        test_object:
          title: Test Object
          type: object
          default:
            age: 23
            email:
              address: bob
              domain: example.com
            name: Bob
          required:
          - age
          - name
          properties:
            age:
              title: Age
              type: number
              x-walrus-ui:
                order: 2
            email:
              properties:
                address:
                  title: Address
                  type: string
                  x-walrus-ui:
                    order: 1
                domain:
                  default: test.com
                  title: Domain
                  type: string
                  x-walrus-ui:
                    order: 2
              required:
              - address
              title: Email
              type: object
              x-walrus-ui:
                colSpan: 12
                order: 3
            name:
              title: Name
              type: string
              x-walrus-ui:
                order: 1
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 1
      x-walrus-ui:
        groupOrder:
        - Basic
